### ISSUE TITLE
Fix Copyright and add Liscense info to file headers

### ISSUE THREAD

**Issue by Jath-Alison** [Jath-Alison/ART#4]
## Overview
So I have no idea how copyright and stuff works for small, non-profit projects like this. What I do know is that distributing the project under a license (I'm currently using MIT license) makes it open source and allows people to copy, share and modify the code.

The question is in the file header comments, it adds copyright info, but I've always left it blank.
'''
/**
 * @file Units.h
 * @author Jath Alison (Jath.Alison@gmail.com)
 * @brief Header containing several Unit classes
 * @version 0.1
 * @date 07-13-2024
 *
 * @copyright Copyright (c) 2024
 *
 * This is the header that needs to be included to use the various Unit classes.
 * The classes aim to aid in dealing with angles and distances by providing a
 * standard form for other classes to use. That way, any of the other units can
 * be used and converted rather than writing seperate functions for different
 * units.
 */
'''

Theres also a '''@licence''' tag that I'd like to use.

## Task

- [ ] Find out what info goes into the copyright info
- [ ] Find out how to properly convey that the project is under the MIT licence
- [ ] Add Both this info to every existing file
- [ ] Mark this issue complete so I can begin adding this to new files

Take a look [here](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://stackoverflow.com/questions/12353409/doxygen-and-license-copyright-informations&ved=2ahUKEwiro_ynz6aHAxXXE0QIHdVpCMAQFnoECBoQAQ&usg=AOvVaw1k1M9qrIgBDpXwdRz_Y6XF)
